config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  #staticpage controller routes
  root 'staticpages#home'

  get '/contact',   to: 'staticpages#contact'

  get '/signin',    to: 'staticpages#signin'

  get '/home',      to: 'staticpages#home'

  get '/help',      to: 'staticpages#help'

  get '/about',     to: 'staticpages#about'

  #user controller routes
  get '/index',     to: 'users#index'
  get '/signup',    to: 'users#new'
  get '/show',      to: 'users#show'
  # delete '/delete', to: 'users#destroy'

  post '/signup',   to: 'users#create'
  get '/edit',      to: 'users#edit'
  patch '/edit',    to: 'users#update'
  resources :users

  #session controller routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  #acount activation controllers routes
  resources :account_activations, only: [:edit]

  #password reset controllers resources
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #micropost delete resources
  resources :usermicroposts,          only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    if logged_in?
        @micropost  = current_user.usermicroposts.build
        @feed_items = current_user.feed.paginate(page: params[:page],per_page:5)
      end
  end

  def help
  end

  def about
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/about.html.erb
<% provide(:title, "About") %>
<p>About</p>

app/views/staticpages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Staticpages#contact</h1>
<p>Find me in app/views/staticpages/contact.html.erb</p>

app/views/staticpages/help.html.erb
<% provide(:title, "Help") %>
<p>Help</p>

app/views/staticpages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the Sample Layout App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>
<% end %>

app/views/staticpages/signin.html.erb
<% provide(:title, "SignIn") %>
<h1>Staticpages#signin</h1>
<p>Find me in app/views/staticpages/signin.html.erb</p>
<%= link_to "SignUp now",signup_path %>

app/views/staticpages/signup.html.erb
<% provide(:title, "SignUp") %>
<h1>Staticpages#signup</h1>
<p>Find me in app/views/staticpages/signup.html.erb</p>
<%= link_to "SignIn now",signin_path %>